### ISSUE TITLE
Broken sass animations without windicss

### ISSUE THREAD

**Issue by Gildedter** [firtadokei/ci-svelte-appstarter#5]
run the following commands:
<pre>
npm uninstall windicss vite-plugin-windicss // removes windicss dependencies
npm add -D sass // enables <a href="https://vitejs.dev/guide/features.html#css-pre-processors">vite's built-in sass</a>
</pre>

other changes:
 deleted file:
`windi.config.js`
removed lines:
https://github.com/firtadokei/ci-svelte-appstarter/blob/8b7725ba12ab2ab40dbae0c863a0b88cd2456310/resources/main.js#L3
https://github.com/firtadokei/ci-svelte-appstarter/blob/8b7725ba12ab2ab40dbae0c863a0b88cd2456310/resources/main.js#L4
https://github.com/firtadokei/ci-svelte-appstarter/blob/8b7725ba12ab2ab40dbae0c863a0b88cd2456310/vite.config.js#L3
https://github.com/firtadokei/ci-svelte-appstarter/blob/8b7725ba12ab2ab40dbae0c863a0b88cd2456310/vite.config.js#L13

**Comment by Gildedter** [comment]
I also delete the lines with `@apply` in main.scss,

I've already trie this [fix](https://github.com/vitejs/vite/issues/832), no dice

**Comment by jaguarch** [comment]
Sorry, could you please be more specific
animations work fine without windicss for me

**Comment by Gildedter** [comment]
I was missing `block`, bootstrap's version was `d-block` sorry bout that
